# 00 — Shared loader and contracts

**Pregunta:** ¿estamos cargando los artifacts correctos y entendiendo sus contratos?

Este notebook no es un reporte financiero. Es el contrato de lectura para el paquete de reportes contables/profesionales.

Responsabilidades:

- localizar el repo y el bundle `public/accounting/latest`;
- verificar artifacts requeridos y opcionales;
- normalizar métricas anuales;
- listar años, monedas, `metric_id`, dimensiones y fuentes;
- detectar problemas de lectura antes de que los reportes narrativos arranquen;
- exportar outputs externos limpios a `out/professional_pack/latest`.

No responsabilidades:

- no recalcula lógica core;
- no clasifica transacciones;
- no decide saldos;
- no inventa caja;
- no suma ARS + USD;
- no cuenta todavía la historia financiera.

In [4]:
from pathlib import Path
import sys
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 120)
pd.set_option("display.max_rows", 200)
pd.set_option("display.width", 240)

cwd = Path.cwd().resolve()
repo_root = None
for p in [cwd, *cwd.parents]:
    if (p / "Makefile").exists() and (p / "accounting").is_dir():
        repo_root = p
        break
if repo_root is None:
    raise FileNotFoundError("Could not find repo root. Run from inside accounting-backend.")

reports_dir = repo_root / "accounting" / "notebooks" / "accounting_reports"
if str(reports_dir) not in sys.path:
    sys.path.insert(0, str(reports_dir))

from _shared import (
    find_repo_root, professional_pack_dir, inspect_artifacts, load_annual_dashboard_metrics,
    metric_inventory, dimension_inventory, qa_findings, build_readiness_summary,
    export_shared_contract_outputs, DEFAULT_REQUIRED_ARTIFACTS, DEFAULT_OPTIONAL_ARTIFACTS,
)

repo_root = find_repo_root(repo_root)
pack_dir = professional_pack_dir(repo_root)
print("repo_root:", repo_root)
print("professional_pack:", pack_dir)

repo_root: /home/matias/repos/accounting-backend
professional_pack: /home/matias/repos/accounting-backend/out/professional_pack/latest

## 1. Artifact registry

Los artifacts **required** son necesarios para que los demás reportes funcionen. Los **optional** agregan QA, drilldown o contexto, pero no deberían romper el 00 si faltan.

In [5]:
artifact_inventory = inspect_artifacts(
    repo_root,
    required=DEFAULT_REQUIRED_ARTIFACTS,
    optional=DEFAULT_OPTIONAL_ARTIFACTS,
)

display(artifact_inventory)

missing_required = artifact_inventory[
    artifact_inventory["required"].eq(True) & ~artifact_inventory["exists"].eq(True)
]

# if not missing_required.empty:
#     display(missing_required)
#     raise FileNotFoundError("Missing required artifacts. Run make run-accounting / publish before report notebooks.")

                   artifact_key  required                                      expected_path  exists    rows  cols                                            columns error
0      annual_dashboard_metrics      True  public/accounting/latest/canonical_dashboard/a...    True   287.0  24.0  metric_id, period_grain, period, period_start,...
1           annual_dashboard_qa      True  public/accounting/latest/canonical_dashboard/a...    True    12.0   4.0                    check, status, detail, severity
2      metric_contract_frontier      True  public/accounting/latest/public_contract/metri...    True    22.0  18.0  metric_id, label, semantic_category, flow_or_s...
3               public_manifest      True              public/accounting/latest/manifest.csv   False     NaN   NaN
4     artifact_contracts_public     False  public/accounting/latest/public_contract/artif...    True    40.0  10.0  name, relpath, artifact_role, accounting_natur...
5           publish_contract_qa     False  public/accounting/latest/qa/publish_contract_q...   False     NaN   NaN
6                release_checks     False  out/professional_pack/latest/qa/release_checks...   False     NaN   NaN
7             validation_report     False           out/metrics/latest/validation_report.csv    True     2.0   4.0                 level, check_name, message, n_rows
8   monthly_operating_statement     False  out/run/accounting/latest/monthly_operating_st...    True  1577.0  15.0  period, period_end, Currency, statement_line, ...
9   monthly_flow_semantic_split     False  out/run/accounting/latest/monthly_flow_semanti...    True   780.0  25.0  period, period_end, Currency, Box, Lugar, acto...
10           monthly_cash_close     False   out/run/accounting/latest/monthly_cash_close.csv    True  2208.0  22.0  period, period_end, as_of_date, Box, party, ac...
11        monthly_debt_position     False  out/run/accounting/latest/monthly_debt_positio...    True   474.0  16.0  period, period_end, as_of_date, debtor, credit...
12        monthly_debt_activity     False  out/run/accounting/latest/monthly_debt_activit...    True  1099.0  20.0  period, period_end, Currency, debtor, creditor...
13   debt_status_reconciliation     False  out/debt_resolution/latest/debt_status_reconci...    True   125.0  12.0  debt_id, source_tx_id, debtor, creditor, curre...
14              debt_open_items     False     out/debt_resolution/latest/debt_open_items.csv    True   125.0  15.0  debt_id, source_tx_id, opened_at, debtor, cred...
15        debt_repayment_events     False  out/debt_resolution/latest/debt_repayment_even...    True    13.0  10.0  repayment_tx_id, repayment_date, debtor, credi...

## 2. Load and normalize annual metrics

Fuente principal:

```text
public/accounting/latest/canonical_dashboard/annual_balance_dashboard_metrics.csv
```

La normalización acá es de lectura/reporting: `period` como año string, `Currency` explícita, `value` numérico, y columnas opcionales presentes.

In [6]:
metrics = load_annual_dashboard_metrics(repo_root)

years = sorted(metrics.loc[metrics["period"].astype(str).str.match(r"^\d{4}$", na=False), "period"].unique().tolist())
currencies = sorted(metrics["Currency"].fillna("N/A").astype(str).unique().tolist())

print("metric rows:", len(metrics))
print("years:", years)
print("currencies:", currencies)
print("metric_ids:", metrics["metric_id"].nunique())

display(metrics.head(30))

metric rows: 287
years: ['2022', '2023', '2024', '2025', '2026']
currencies: ['ARS', 'N/A', 'USD']
metric_ids: 37

,metric_id,period_grain,period,period_start,period_end,Currency,value,value_status,flow_or_stock,accounting_section,dashboard_section,dimension_name,dimension_value,source_table,source_filter,calculation_rule,frontend_suitability,public_flag,internal_flag,legacy_flag,validation_status,caveat,run_id,as_of_date,format_hint
0,IS.REVENUE.OPERATING,Y,2022,2022-01-01,2022-12-31,ARS,4948804.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=operating_revenue,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
1,IS.REVENUE.OPERATING,Y,2023,2023-01-01,2023-12-31,ARS,9141302.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=operating_revenue,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
2,IS.REVENUE.OPERATING,Y,2023,2023-01-01,2023-12-31,USD,0.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=operating_revenue,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
3,IS.REVENUE.OPERATING,Y,2024,2024-01-01,2024-12-31,ARS,13558336.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=operating_revenue,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
4,IS.REVENUE.OPERATING,Y,2024,2024-01-01,2024-12-31,USD,3610.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=operating_revenue,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
5,IS.REVENUE.OPERATING,Y,2025,2025-01-01,2025-12-31,ARS,40125422.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=operating_revenue,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
6,IS.REVENUE.OPERATING,Y,2025,2025-01-01,2025-12-31,USD,4560.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=operating_revenue,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
7,IS.REVENUE.OPERATING,Y,2026,2026-01-01,2026-12-31,ARS,29589000.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=operating_revenue,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
8,IS.REVENUE.OPERATING,Y,2026,2026-01-01,2026-12-31,USD,2280.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=operating_revenue,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
9,IS.OPEX.PROPERTY,Y,2022,2022-01-01,2022-12-31,ARS,587266.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=property_opex_true,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
10,IS.OPEX.PROPERTY,Y,2023,2023-01-01,2023-12-31,ARS,2392541.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=property_opex_true,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
11,IS.OPEX.PROPERTY,Y,2023,2023-01-01,2023-12-31,USD,0.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=property_opex_true,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
12,IS.OPEX.PROPERTY,Y,2024,2024-01-01,2024-12-31,ARS,8066301.84,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=property_opex_true,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
13,IS.OPEX.PROPERTY,Y,2024,2024-01-01,2024-12-31,USD,0.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=property_opex_true,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
14,IS.OPEX.PROPERTY,Y,2025,2025-01-01,2025-12-31,ARS,11955360.74,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=property_opex_true,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
15,IS.OPEX.PROPERTY,Y,2025,2025-01-01,2025-12-31,USD,0.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=property_opex_true,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
16,IS.OPEX.PROPERTY,Y,2026,2026-01-01,2026-12-31,ARS,6739472.24,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=property_opex_true,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
17,IS.OPEX.PROPERTY,Y,2026,2026-01-01,2026-12-31,USD,0.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=property_opex_true,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
18,IS.NET.OPERATING,Y,2022,2022-01-01,2022-12-31,ARS,4361538.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=net_operating,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
19,IS.NET.OPERATING,Y,2023,2023-01-01,2023-12-31,ARS,6748761.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=net_operating,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
20,IS.NET.OPERATING,Y,2023,2023-01-01,2023-12-31,USD,0.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=net_operating,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
21,IS.NET.OPERATING,Y,2024,2024-01-01,2024-12-31,ARS,5492034.16,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=net_operating,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
22,IS.NET.OPERATING,Y,2024,2024-01-01,2024-12-31,USD,3610.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=net_operating,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
23,IS.NET.OPERATING,Y,2025,2025-01-01,2025-12-31,ARS,28170061.26,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=net_operating,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
24,IS.NET.OPERATING,Y,2025,2025-01-01,2025-12-31,USD,4560.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=net_operating,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
25,IS.NET.OPERATING,Y,2026,2026-01-01,2026-12-31,ARS,22849527.76,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=net_operating,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
26,IS.NET.OPERATING,Y,2026,2026-01-01,2026-12-31,USD,2280.00,available,flow,income_statement,1. Operating result,,,monthly_operating_statement.csv,statement_line=net_operating,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
27,FUND.CONTRIB.TOTAL,Y,2022,2022-01-01,2022-12-31,ARS,0.00,available,flow,coverage,2. Funding and distributions,,,monthly_operating_statement.csv,statement_line=funding_contributions,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
28,FUND.CONTRIB.TOTAL,Y,2023,2023-01-01,2023-12-31,ARS,0.00,available,flow,coverage,2. Funding and distributions,,,monthly_operating_statement.csv,statement_line=funding_contributions,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,
29,FUND.CONTRIB.TOTAL,Y,2023,2023-01-01,2023-12-31,USD,0.00,available,flow,coverage,2. Funding and distributions,,,monthly_operating_statement.csv,statement_line=funding_contributions,annual flow = sum monthly flow by year and cur...,safe_with_caveat,True,False,False,ok,,20260701T190254Z,2026-07-01,

## 3. Readiness summary

Resumen corto para saber si el resto del pack puede correr y con qué salvedades.

In [7]:
metric_inv = metric_inventory(metrics)
dimension_inv = dimension_inventory(metrics)
qa = qa_findings(metrics, artifact_inventory)
readiness = build_readiness_summary(repo_root, metrics, artifact_inventory, qa)

display(readiness)
display(qa)

                          field                                  value
0                     repo_root  /home/matias/repos/accounting-backend
1               years_available           2022, 2023, 2024, 2025, 2026
2          currencies_available                          ARS, N/A, USD
3                   metric_rows                                    287
4                    metric_ids                                     37
5    required_artifacts_missing                                      1
6                   qa_failures                                      1
7                   qa_warnings                                      1
8             run_latest_target                       20260701T190254Z
9         metrics_latest_target                       20260701T190254Z
10           debt_latest_target                       20260701T190254Z
11  human_reports_latest_target                       20260701T190254Z

  severity       area                         check                                             detail
0     fail  artifacts      required_artifact_exists  public_manifest missing at public/accounting/l...
1       ok    metrics    available_metric_has_value                No available metrics with NaN value
2       ok   currency      no_cross_currency_totals  No suspicious cross-currency Currency labels f...
3       ok       cash  cash_frontend_safe_available                  5 cash rows have available values
4  warning    display   hidden_metric_id_collisions  50 display key combinations map to more than o...

## 4. Metric inventory

Este inventario es el mapa de qué puede consumir cada notebook. No debe ser interpretado como reporte final; es un índice técnico/humano de métricas disponibles.

In [8]:
display(metric_inv)

operating_metrics = metric_inv[metric_inv["metric_id"].astype(str).str.startswith("IS.")]
funding_distribution_metrics = metric_inv[metric_inv["metric_id"].astype(str).str.startswith(("FUND.", "DIST.", "COV."))]
cash_metrics = metric_inv[metric_inv["metric_id"].astype(str).str.startswith(("BS.CASH", "DQ.CASH"))]
debt_metrics = metric_inv[metric_inv["metric_id"].astype(str).str.startswith("ID.DEBT")]
dq_metrics = metric_inv[metric_inv["metric_id"].astype(str).str.startswith("DQ.")]

print("operating metrics:", len(operating_metrics))
print("funding/distribution/coverage metrics:", len(funding_distribution_metrics))
print("cash metrics:", len(cash_metrics))
print("debt metrics:", len(debt_metrics))
print("DQ metrics:", len(dq_metrics))

,metric_id,dashboard_section,Currency,dimension_name,dimension_value,n_rows,n_values,min_value,max_value,periods,value_status,source_table,caveat,metric_label
0,BS.CASH.CLOSE.BOX,3. Cash and liquidity,N/A,,,1,0,NaN,NaN,nan,unavailable,monthly_cash_close.csv,No frontend-safe cash rows exist; no fallback ...,Caja validada por box
1,BS.CASH.FB,7. Legacy reconciliation,N/A,,,1,0,NaN,NaN,nan,not_applicable,metric_contract_frontier.csv,Legacy/reconciliation only unless rebuilt from...,BS.CASH.FB
2,BS.CASH.PM,7. Legacy reconciliation,N/A,,,1,0,NaN,NaN,nan,not_applicable,metric_contract_frontier.csv,Legacy/reconciliation only unless rebuilt from...,BS.CASH.PM
3,BS.CASH.TOTAL,3. Cash and liquidity,N/A,,,1,0,NaN,NaN,nan,unavailable,monthly_cash_close.csv,No frontend-safe cash rows exist; no fallback ...,Caja validada total
4,COV.NET.AFTER_DRAWS,2. Funding and distributions,ARS,,,5,5,-6.434288e+06,0.00,"2022, 2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,Cobertura después de funding y retiros
5,COV.NET.AFTER_DRAWS,2. Funding and distributions,USD,,,4,4,0.000000e+00,4560.00,"2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,Cobertura después de funding y retiros
6,COV.SAVINGS_RATE,2. Funding and distributions,ARS,,,5,5,-1.171567e+00,0.00,"2022, 2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,Ratio of annual aggregates; not an average of ...,Savings / coverage rate
7,COV.SAVINGS_RATE,2. Funding and distributions,USD,,,4,3,9.166667e-01,1.00,"2023, 2024, 2025, 2026","available, not_applicable",monthly_operating_statement.csv,Ratio of annual aggregates; not an average of ...,Savings / coverage rate
8,DIST.DIVIDENDS,2. Funding and distributions,ARS,,,5,5,0.000000e+00,682384.00,"2022, 2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,Dividendos
9,DIST.DIVIDENDS,2. Funding and distributions,USD,,,4,4,0.000000e+00,190.00,"2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,Dividendos
10,DIST.DRAWS.BY_TYPE,2. Funding and distributions,ARS,semantic_subbucket,dividend,1,1,6.823840e+05,682384.00,2026,available,monthly_flow_semantic_split.csv,,DIST.DRAWS.BY_TYPE
11,DIST.DRAWS.BY_TYPE,2. Funding and distributions,ARS,semantic_subbucket,personal_expense,5,5,4.361538e+06,32805691.00,"2022, 2023, 2024, 2025, 2026",available,monthly_flow_semantic_split.csv,,DIST.DRAWS.BY_TYPE
12,DIST.DRAWS.BY_TYPE,2. Funding and distributions,USD,semantic_subbucket,dividend,2,2,1.000000e+02,190.00,"2024, 2026",available,monthly_flow_semantic_split.csv,,DIST.DRAWS.BY_TYPE
13,DIST.DRAWS.PERSONAL,2. Funding and distributions,ARS,,,5,5,4.361538e+06,32805691.00,"2022, 2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,Retiros / gasto personal
14,DIST.DRAWS.PERSONAL,2. Funding and distributions,USD,,,4,4,0.000000e+00,190.00,"2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,Retiros / gasto personal
15,DQ.CASH.FRONTEND_SAFE,3. Cash and liquidity,N/A,,,5,5,0.000000e+00,0.00,"2022, 2023, 2024, 2025, 2026",available,monthly_cash_close.csv,,Cash frontend-safe
16,DQ.CLASSIFICATION.COVERAGE,6. Data quality and caveats,ARS,,,5,5,8.981727e-01,1.00,"2022, 2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,Cobertura de clasificación
17,DQ.CLASSIFICATION.COVERAGE,6. Data quality and caveats,USD,,,4,4,3.518519e-01,1.00,"2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,Cobertura de clasificación
18,DQ.DEBT.ACTIVITY.RECONCILIATION,6. Data quality and caveats,N/A,,,4,4,1.610000e+02,399.00,"2023, 2024, 2025, 2026",available,monthly_debt_activity.csv,,Reconciliación actividad de deuda
19,DQ.OPEX.LEAKAGE.AMOUNT,6. Data quality and caveats,N/A,,,1,0,NaN,NaN,nan,unavailable,semantic_leakage_qa.csv,canonical source missing or required dimension...,OPEX leakage detectado
20,DQ.UNKNOWN.AMOUNT,6. Data quality and caveats,ARS,,,5,5,0.000000e+00,2164500.00,"2022, 2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,Importe unknown / review-required
21,DQ.UNKNOWN.AMOUNT,6. Data quality and caveats,USD,,,4,4,0.000000e+00,1930.00,"2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,Importe unknown / review-required
22,FUND.CONTRIB.BY_ACTOR,2. Funding and distributions,ARS,actor,Household,2,2,1.422000e+06,3010000.00,"2024, 2025",available,monthly_flow_semantic_split.csv,,Funding por actor
23,FUND.CONTRIB.BY_ACTOR,2. Funding and distributions,ARS,actor,Property Management,2,2,2.100000e+05,682001.00,"2024, 2025",available,monthly_flow_semantic_split.csv,,Funding por actor
24,FUND.CONTRIB.TOTAL,2. Funding and distributions,ARS,,,5,5,0.000000e+00,3692001.00,"2022, 2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,Funding / aportes
25,FUND.CONTRIB.TOTAL,2. Funding and distributions,USD,,,4,4,0.000000e+00,0.00,"2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,Funding / aportes
26,ID.DEBT.ACTIVITY.ADJUSTMENTS,5. Debt activity,USD,debtor_creditor,Alejandro -> MI,3,3,0.000000e+00,0.00,"2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Ajustes residuales
27,ID.DEBT.ACTIVITY.ADJUSTMENTS,5. Debt activity,USD,debtor_creditor,Alejandro -> PM,4,4,0.000000e+00,0.00,"2023, 2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Ajustes residuales
28,ID.DEBT.ACTIVITY.ADJUSTMENTS,5. Debt activity,USD,debtor_creditor,Hector -> MI,2,2,0.000000e+00,0.00,"2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Ajustes residuales
29,ID.DEBT.ACTIVITY.ADJUSTMENTS,5. Debt activity,USD,debtor_creditor,PM -> MI,4,4,-2.000000e+02,193.00,"2023, 2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Ajustes residuales
30,ID.DEBT.ACTIVITY.ADJUSTMENTS,5. Debt activity,USD,debtor_creditor,PM -> Primos,4,4,0.000000e+00,0.00,"2023, 2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Ajustes residuales
31,ID.DEBT.ACTIVITY.INTEREST_ACCRUED,5. Debt activity,USD,debtor_creditor,Alejandro -> MI,3,3,7.300000e+01,84.00,"2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Intereses devengados
32,ID.DEBT.ACTIVITY.INTEREST_ACCRUED,5. Debt activity,USD,debtor_creditor,Alejandro -> PM,4,4,0.000000e+00,0.00,"2023, 2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Intereses devengados
33,ID.DEBT.ACTIVITY.INTEREST_ACCRUED,5. Debt activity,USD,debtor_creditor,Hector -> MI,2,2,0.000000e+00,15.00,"2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Intereses devengados
34,ID.DEBT.ACTIVITY.INTEREST_ACCRUED,5. Debt activity,USD,debtor_creditor,PM -> MI,4,4,0.000000e+00,200.00,"2023, 2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Intereses devengados
35,ID.DEBT.ACTIVITY.INTEREST_ACCRUED,5. Debt activity,USD,debtor_creditor,PM -> Primos,4,4,0.000000e+00,0.00,"2023, 2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Intereses devengados
36,ID.DEBT.ACTIVITY.NET_CHANGE,5. Debt activity,USD,debtor_creditor,Alejandro -> MI,3,3,8.100000e+01,253.00,"2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Cambio neto de deuda
37,ID.DEBT.ACTIVITY.NET_CHANGE,5. Debt activity,USD,debtor_creditor,Alejandro -> PM,4,4,-1.890000e+02,6703.20,"2023, 2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Cambio neto de deuda
38,ID.DEBT.ACTIVITY.NET_CHANGE,5. Debt activity,USD,debtor_creditor,Hector -> MI,2,2,1.500000e+01,490.00,"2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Cambio neto de deuda
39,ID.DEBT.ACTIVITY.NET_CHANGE,5. Debt activity,USD,debtor_creditor,PM -> MI,4,4,-4.686700e+03,5792.20,"2023, 2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Cambio neto de deuda
40,ID.DEBT.ACTIVITY.NET_CHANGE,5. Debt activity,USD,debtor_creditor,PM -> Primos,4,4,0.000000e+00,897.00,"2023, 2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Cambio neto de deuda
41,ID.DEBT.ACTIVITY.NEW_CLAIMS,5. Debt activity,USD,debtor_creditor,Alejandro -> MI,3,3,0.000000e+00,180.00,"2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Nuevos claims / adelantos
42,ID.DEBT.ACTIVITY.NEW_CLAIMS,5. Debt activity,USD,debtor_creditor,Alejandro -> PM,4,4,0.000000e+00,6703.20,"2023, 2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Nuevos claims / adelantos
43,ID.DEBT.ACTIVITY.NEW_CLAIMS,5. Debt activity,USD,debtor_creditor,Hector -> MI,2,2,0.000000e+00,490.00,"2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Nuevos claims / adelantos
44,ID.DEBT.ACTIVITY.NEW_CLAIMS,5. Debt activity,USD,debtor_creditor,PM -> MI,4,4,0.000000e+00,5806.20,"2023, 2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Nuevos claims / adelantos
45,ID.DEBT.ACTIVITY.NEW_CLAIMS,5. Debt activity,USD,debtor_creditor,PM -> Primos,4,4,0.000000e+00,897.00,"2023, 2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Nuevos claims / adelantos
46,ID.DEBT.ACTIVITY.REPAYMENTS,5. Debt activity,USD,debtor_creditor,Alejandro -> MI,3,3,0.000000e+00,0.00,"2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Repagos de deuda interna
47,ID.DEBT.ACTIVITY.REPAYMENTS,5. Debt activity,USD,debtor_creditor,Alejandro -> PM,4,4,0.000000e+00,189.00,"2023, 2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Repagos de deuda interna
48,ID.DEBT.ACTIVITY.REPAYMENTS,5. Debt activity,USD,debtor_creditor,Hector -> MI,2,2,0.000000e+00,0.00,"2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Repagos de deuda interna
49,ID.DEBT.ACTIVITY.REPAYMENTS,5. Debt activity,USD,debtor_creditor,PM -> MI,4,4,9.000000e+01,4686.70,"2023, 2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Repagos de deuda interna
50,ID.DEBT.ACTIVITY.REPAYMENTS,5. Debt activity,USD,debtor_creditor,PM -> Primos,4,4,0.000000e+00,0.00,"2023, 2024, 2025, 2026",available,monthly_debt_activity.csv,Debt movement; not OPEX or funding unless clas...,Repagos de deuda interna
51,ID.DEBT.INTEREST.OPEN,4. Internal debt and claims,USD,,,4,4,0.000000e+00,253.00,"2023, 2024, 2025, 2026",available,monthly_debt_position.csv,"Debt is stock, not flow; not mixed into operat...",Interés abierto
52,ID.DEBT.NET_PM_POSITION,4. Internal debt and claims,USD,,,4,4,0.000000e+00,0.00,"2023, 2024, 2025, 2026",available,monthly_debt_position.csv,,ID.DEBT.NET_PM_POSITION
53,ID.DEBT.OPEN.BY_COUNTERPARTY,4. Internal debt and claims,USD,debtor_creditor,Alejandro -> MI,3,3,2.530000e+02,418.00,"2024, 2025, 2026",available,monthly_debt_position.csv,,Saldos abiertos por contraparte
54,ID.DEBT.OPEN.BY_COUNTERPARTY,4. Internal debt and claims,USD,debtor_creditor,Alejandro -> PM,4,4,6.514200e+03,6703.20,"2023, 2024, 2025, 2026",available,monthly_debt_position.csv,,Saldos abiertos por contraparte
55,ID.DEBT.OPEN.BY_COUNTERPARTY,4. Internal debt and claims,USD,debtor_creditor,Hector -> MI,2,2,4.900000e+02,505.00,"2025, 2026",available,monthly_debt_position.csv,,Saldos abiertos por contraparte
56,ID.DEBT.OPEN.BY_COUNTERPARTY,4. Internal debt and claims,USD,debtor_creditor,PM -> MI,4,4,2.116000e+03,8536.20,"2023, 2024, 2025, 2026",available,monthly_debt_position.csv,,Saldos abiertos por contraparte
57,ID.DEBT.OPEN.BY_COUNTERPARTY,4. Internal debt and claims,USD,debtor_creditor,PM -> Primos,4,4,8.970000e+02,897.00,"2023, 2024, 2025, 2026",available,monthly_debt_position.csv,,Saldos abiertos por contraparte
58,ID.DEBT.PRINCIPAL.OPEN,4. Internal debt and claims,USD,,,4,4,1.019720e+04,16316.40,"2023, 2024, 2025, 2026",available,monthly_debt_position.csv,"Debt is stock, not flow; not mixed into operat...",Principal abierto
59,ID.DEBT.TOTAL.OPEN,4. Internal debt and claims,USD,,,4,4,1.045020e+04,16389.40,"2023, 2024, 2025, 2026",available,monthly_debt_position.csv,"Debt is stock, not flow; not mixed into operat...",Deuda total abierta
60,IS.CONTRIB.TOTAL,7. Legacy reconciliation,N/A,,,1,0,NaN,NaN,nan,not_applicable,metric_contract_frontier.csv,Legacy/reconciliation only unless rebuilt from...,IS.CONTRIB.TOTAL
61,IS.DRAWS.PERSONAL,7. Legacy reconciliation,N/A,,,1,0,NaN,NaN,nan,not_applicable,metric_contract_frontier.csv,Legacy/reconciliation only unless rebuilt from...,IS.DRAWS.PERSONAL
62,IS.INCOME.TOTAL,7. Legacy reconciliation,N/A,,,1,0,NaN,NaN,nan,not_applicable,metric_contract_frontier.csv,Legacy/reconciliation only unless rebuilt from...,IS.INCOME.TOTAL
63,IS.NET.AFTER_COSTS,7. Legacy reconciliation,N/A,,,1,0,NaN,NaN,nan,not_applicable,metric_contract_frontier.csv,Legacy/reconciliation only unless rebuilt from...,IS.NET.AFTER_COSTS
64,IS.NET.OPERATING,1. Operating result,ARS,,,5,5,4.361538e+06,28170061.26,"2022, 2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,Resultado operativo neto
65,IS.NET.OPERATING,1. Operating result,USD,,,4,4,0.000000e+00,4560.00,"2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,Resultado operativo neto
66,IS.NET.POST_DRAWS,7. Legacy reconciliation,N/A,,,1,0,NaN,NaN,nan,not_applicable,metric_contract_frontier.csv,Legacy/reconciliation only unless rebuilt from...,IS.NET.POST_DRAWS
67,IS.OPEX.BY_CATEGORY,1. Operating result,ARS,semantic_subbucket,legal,4,4,3.770000e+04,1044210.00,"2022, 2023, 2024, 2025",available,monthly_flow_semantic_split.csv,,OPEX por categoría
68,IS.OPEX.BY_CATEGORY,1. Operating result,ARS,semantic_subbucket,maintenance,4,4,5.750000e+04,1131802.18,"2022, 2023, 2024, 2025",available,monthly_flow_semantic_split.csv,,OPEX por categoría
69,IS.OPEX.BY_CATEGORY,1. Operating result,ARS,semantic_subbucket,services,5,5,1.057260e+05,3799578.25,"2022, 2023, 2024, 2025, 2026",available,monthly_flow_semantic_split.csv,,OPEX por categoría
70,IS.OPEX.BY_CATEGORY,1. Operating result,ARS,semantic_subbucket,taxes,5,5,2.279400e+05,6876980.31,"2022, 2023, 2024, 2025, 2026",available,monthly_flow_semantic_split.csv,,OPEX por categoría
71,IS.OPEX.PROPERTY,1. Operating result,ARS,,,5,5,5.872660e+05,11955360.74,"2022, 2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,OPEX propiedad
72,IS.OPEX.PROPERTY,1. Operating result,USD,,,4,4,0.000000e+00,0.00,"2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,OPEX propiedad
73,IS.RENT.BY_PROPERTY,1. Operating result,ARS,Lugar,CABA,4,4,8.000000e+05,1710000.00,"2022, 2023, 2025, 2026",available,monthly_flow_semantic_split.csv,,Renta por propiedad
74,IS.RENT.BY_PROPERTY,1. Operating result,ARS,Lugar,Tigre 01,5,5,1.686700e+06,18021572.00,"2022, 2023, 2024, 2025, 2026",available,monthly_flow_semantic_split.csv,,Renta por propiedad
75,IS.RENT.BY_PROPERTY,1. Operating result,ARS,Lugar,Tigre 28,5,5,1.223120e+06,10060000.00,"2022, 2023, 2024, 2025, 2026",available,monthly_flow_semantic_split.csv,,Renta por propiedad
76,IS.RENT.BY_PROPERTY,1. Operating result,ARS,Lugar,Tigre 32,5,5,1.056984e+06,11243850.00,"2022, 2023, 2024, 2025, 2026",available,monthly_flow_semantic_split.csv,,Renta por propiedad
77,IS.RENT.BY_PROPERTY,1. Operating result,USD,Lugar,CABA,3,3,2.280000e+03,4560.00,"2024, 2025, 2026",available,monthly_flow_semantic_split.csv,,Renta por propiedad
78,IS.RENT.TOTAL,1. Operating result,ARS,,,5,5,4.948804e+06,40125422.00,"2022, 2023, 2024, 2025, 2026",available,monthly_flow_semantic_split.csv,,Renta total
79,IS.RENT.TOTAL,1. Operating result,USD,,,3,3,2.280000e+03,4560.00,"2024, 2025, 2026",available,monthly_flow_semantic_split.csv,,Renta total
80,IS.REVENUE.OPERATING,1. Operating result,ARS,,,5,5,4.948804e+06,40125422.00,"2022, 2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,Ingresos operativos
81,IS.REVENUE.OPERATING,1. Operating result,USD,,,4,4,0.000000e+00,4560.00,"2023, 2024, 2025, 2026",available,monthly_operating_statement.csv,,Ingresos operativos

operating metrics: 22
funding/distribution/coverage metrics: 15
cash metrics: 5
debt metrics: 34
DQ metrics: 7

## 5. Dimension inventory

Este inventario ayuda a detectar cómo vienen las métricas dimensionadas: por propiedad, categoría semántica, actor, debtor/creditor, o `cash_path` cuando esté disponible.

Regla de reporting: si una dimensión es importante para interpretación humana, no debe quedar escondida solo dentro del `line` label; los notebooks posteriores pueden promoverla a columna.

In [9]:
display(dimension_inv)

        dimension_name      dimension_value  n_metric_ids                                         metric_ids  n_rows     currencies                            periods
0                                                      27  BS.CASH.CLOSE.BOX, BS.CASH.FB, BS.CASH.PM, BS....     133  ARS, N/A, USD  2022, 2023, 2024, 2025, 2026, nan
1                Lugar                 CABA             1                                IS.RENT.BY_PROPERTY       7       ARS, USD       2022, 2023, 2024, 2025, 2026
2                Lugar             Tigre 01             1                                IS.RENT.BY_PROPERTY       5            ARS       2022, 2023, 2024, 2025, 2026
3                Lugar             Tigre 28             1                                IS.RENT.BY_PROPERTY       5            ARS       2022, 2023, 2024, 2025, 2026
4                Lugar             Tigre 32             1                                IS.RENT.BY_PROPERTY       5            ARS       2022, 2023, 2024, 2025, 2026
5                actor            Household             1                              FUND.CONTRIB.BY_ACTOR       2            ARS                         2024, 2025
6                actor  Property Management             1                              FUND.CONTRIB.BY_ACTOR       2            ARS                         2024, 2025
7      debtor_creditor      Alejandro -> MI             6  ID.DEBT.ACTIVITY.ADJUSTMENTS, ID.DEBT.ACTIVITY...      18            USD                   2024, 2025, 2026
8      debtor_creditor      Alejandro -> PM             6  ID.DEBT.ACTIVITY.ADJUSTMENTS, ID.DEBT.ACTIVITY...      24            USD             2023, 2024, 2025, 2026
9      debtor_creditor         Hector -> MI             6  ID.DEBT.ACTIVITY.ADJUSTMENTS, ID.DEBT.ACTIVITY...      12            USD                         2025, 2026
10     debtor_creditor             PM -> MI             6  ID.DEBT.ACTIVITY.ADJUSTMENTS, ID.DEBT.ACTIVITY...      24            USD             2023, 2024, 2025, 2026
11     debtor_creditor         PM -> Primos             6  ID.DEBT.ACTIVITY.ADJUSTMENTS, ID.DEBT.ACTIVITY...      24            USD             2023, 2024, 2025, 2026
12  semantic_subbucket             dividend             1                                 DIST.DRAWS.BY_TYPE       3       ARS, USD                         2024, 2026
13  semantic_subbucket                legal             1                                IS.OPEX.BY_CATEGORY       4            ARS             2022, 2023, 2024, 2025
14  semantic_subbucket          maintenance             1                                IS.OPEX.BY_CATEGORY       4            ARS             2022, 2023, 2024, 2025
15  semantic_subbucket     personal_expense             1                                 DIST.DRAWS.BY_TYPE       5            ARS       2022, 2023, 2024, 2025, 2026
16  semantic_subbucket             services             1                                IS.OPEX.BY_CATEGORY       5            ARS       2022, 2023, 2024, 2025, 2026
17  semantic_subbucket                taxes             1                                IS.OPEX.BY_CATEGORY       5            ARS       2022, 2023, 2024, 2025, 2026

## 6. QA checks del shared loader

Estos checks no reemplazan `scripts/check_release.py` ni QA del backend. Son checks de lectura para evitar reportes humanos engañosos.

In [10]:
display(qa)

available_nan = metrics[
    metrics["value_status"].astype(str).str.lower().eq("available")
    & metrics["value"].isna()
]
if not available_nan.empty:
    print("Rows with value_status=available but NaN value:")
    display(available_nan.head(100))

suspicious_currency = metrics[
    metrics["Currency"].astype(str).isin(["ALL", "Mixed", "ARS+USD", "MULTI", ""])
]
if not suspicious_currency.empty:
    print("Suspicious cross-currency rows:")
    display(suspicious_currency.head(100))

  severity       area                         check                                             detail
0     fail  artifacts      required_artifact_exists  public_manifest missing at public/accounting/l...
1       ok    metrics    available_metric_has_value                No available metrics with NaN value
2       ok   currency      no_cross_currency_totals  No suspicious cross-currency Currency labels f...
3       ok       cash  cash_frontend_safe_available                  5 cash rows have available values
4  warning    display   hidden_metric_id_collisions  50 display key combinations map to more than o...

## 7. Professional interpretation guardrails

| Área | Regla |
|---|---|
| Operación | Renta/OPEX/resultado operativo no incluye funding, deuda, dividendos ni gasto personal. |
| Funding | Un aporte no es ingreso operativo. |
| Distribuciones | Retiros, gasto personal y dividendos no son OPEX de propiedad. |
| Deuda | Deuda interna no es OPEX; debe tratarse como stock/flow financiero entre actores. |
| Caja | Si no existe `validated_cash_close` frontend-safe, caja real debe mostrarse como `s/d`. |
| Moneda | ARS y USD pueden convivir como filas con `Currency`, pero nunca se suman. |
| Box | `Box` puede ser órbita de gobernanza, no caja física. |
| Settlement | Pagos directos de inquilinos/actores cancelan obligaciones pero no implican caja PM/FB. |
| QA | `unavailable` debe mostrarse; no equivale a cero. |

## 8. Export shared outputs

Outputs mínimos:

```text
out/professional_pack/latest/shared_contract_inventory.csv
out/professional_pack/latest/shared_contract_summary.md
```

También exporta inventarios auxiliares a `tables/` y `qa/`.

In [11]:
exported = export_shared_contract_outputs(
    repo_root=repo_root,
    artifact_inventory=artifact_inventory,
    readiness=readiness,
    qa=qa,
    metric_inventory_df=metric_inv,
    dimension_inventory_df=dimension_inv,
)

for key, path in exported.items():
    print(f"{key}: {path.relative_to(repo_root)}")

shared_contract_inventory: out/professional_pack/latest/shared_contract_inventory.csv
shared_contract_summary: out/professional_pack/latest/shared_contract_summary.md
readiness_summary: out/professional_pack/latest/qa/shared_readiness_summary.csv
qa_findings: out/professional_pack/latest/qa/shared_loader_qa.csv
metric_inventory: out/professional_pack/latest/tables/shared_metric_inventory.csv
dimension_inventory: out/professional_pack/latest/tables/shared_dimension_inventory.csv

## 9. Next notebooks enabled by this contract

Propuesta gobernada:

```text
01_balance_dashboard_overview.ipynb
02_cash_and_liquidity.ipynb
03_income_rent_and_operations.ipynb
04_debt_open_items_and_reconciliation.ipynb
05_family_human_storypack.ipynb
```

Cada una debe responder una pregunta humana distinta y exportar outputs propios, sin recalcular lógica core.