# 01 — Balance dashboard overview

**Pregunta humana:** ¿Cuál es la foto anual del sistema patrimonial?

Este reporte es ejecutivo. Integra operación, funding/distribuciones, posición operativa, deuda y QA, sin intentar reemplazar los reportes específicos.

Reglas:

- `Currency` queda como columna junto a la métrica/línea.
- ARS y USD conviven, pero nunca se suman.
- Caja real no se inventa: si no hay fuente frontend-safe, se muestra como `s/d`.
- Funding no es ingreso operativo.
- Deuda interna no es OPEX.
- Retiros/dividendos no son gastos de propiedad.

In [1]:

from pathlib import Path
import sys
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", 160)
pd.set_option("display.max_rows", 220)
pd.set_option("display.width", 260)

cwd = Path.cwd().resolve()
repo_root = None
for p in [cwd, *cwd.parents]:
    if (p / "Makefile").exists() and (p / "accounting").is_dir():
        repo_root = p
        break
if repo_root is None:
    raise FileNotFoundError("Could not find repo root. Run from inside accounting-backend.")

reports_dir = repo_root / "accounting" / "notebooks" / "accounting_reports"
if str(reports_dir) not in sys.path:
    sys.path.insert(0, str(reports_dir))

from _shared import *

repo_root = find_repo_root(repo_root)
pack_dir = professional_pack_dir(repo_root)

artifact_inventory = inspect_artifacts(repo_root)
metrics = load_annual_dashboard_metrics(repo_root)
annual_qa = load_annual_dashboard_qa(repo_root)
debt_status = load_debt_status_reconciliation(repo_root)

years = available_years(metrics)
currencies = available_currencies(metrics)
extended_qa = extended_qa_findings(metrics, artifact_inventory, debt_status)

print("repo_root:", repo_root)
print("pack_dir:", pack_dir)
print("years:", years)
print("currencies:", currencies)
print("metric rows:", len(metrics))

repo_root: /home/matias/repos/accounting-backend
pack_dir: /home/matias/repos/accounting-backend/out/professional_pack/latest
years: ['2022', '2023', '2024', '2025', '2026']
currencies: ['ARS', 'N/A', 'USD']
metric rows: 350

## 1. QA extendido de lectura

Este bloque reconcilia la notebook anterior con los checks extendidos: métricas `available` sin valor, colisiones de etiquetas al ocultar `metric_id`, cash no frontend-safe, cross-currency y deuda engine-vs-ledger.

In [ ]:
display(short_status_table(extended_qa))
export_table(extended_qa, repo_root, "overview_extended_qa.csv")

  severity       area                         check   n                                             detail
0     fail  artifacts      required_artifacts_exist   1                           Missing: public_manifest
3       ok       cash  cash_frontend_safe_available   5                              5 available cash rows
2       ok   currency      no_cross_currency_totals   0  No suspicious cross-currency Currency labels f...
1       ok    metrics    available_metric_has_value   0               No available metrics with NaN values
4  warning    display   hidden_metric_id_collisions  59  59 display key groups map to multiple metric_i...
5  warning    metrics           unavailable_visible   7  7 unavailable/blocked rows should be surfaced ...

wrote: /home/matias/repos/accounting-backend/out/professional_pack/latest/tables/overview_extended_qa.csv rows=6 cols=5

PosixPath('/home/matias/repos/accounting-backend/out/professional_pack/latest/tables/overview_extended_qa.csv')

## 2. Executive summary

Lectura profesional preliminar:

- La operación patrimonial parece generar resultado operativo positivo.
- Los retiros/distribuciones tienden a absorber gran parte del resultado operativo.
- La caja real todavía no es auditable si no existe `validated_cash_close`.
- La deuda interna en USD está mejor modelada y debería mirarse como stock/flow separado.
- El sistema opera como una red de gobernanza, pagos directos, claims y deuda; no como una caja única.

In [3]:
overview_specs = [
    spec("Overview", "Resultado operativo", "Renta total", "IS.RENT.TOTAL", 100,
         professional_comment="Ingreso operativo propio de la explotación patrimonial. No incluye funding ni deuda."),
    spec("Overview", "Resultado operativo", "OPEX propiedad", "IS.OPEX.PROPERTY", 200,
         professional_comment="Costos operativos de propiedad: impuestos, servicios, mantenimiento, legal y otros OPEX reales."),
    spec("Overview", "Resultado operativo", "Resultado operativo neto", "IS.NET.OPERATING", 300,
         professional_comment="Renta menos OPEX de propiedad. Es la medida más limpia de performance operativa."),
    spec("Overview", "Funding y distribuciones", "Funding / aportes", "FUND.CONTRIB.TOTAL", 400,
         professional_comment="Aportes para sostener caja o cubrir necesidades. No es ingreso operativo."),
    spec("Overview", "Funding y distribuciones", "Retiros / gasto personal", "DIST.DRAWS.PERSONAL", 500,
         professional_comment="Salidas hacia gasto personal/familiar. No es OPEX de propiedades."),
    spec("Overview", "Funding y distribuciones", "Dividendos", "DIST.DIVIDENDS", 510,
         professional_comment="Distribuciones patrimoniales. Deben separarse de gasto operativo."),
    spec("Overview", "Funding y distribuciones", "Cobertura después de funding y retiros", "COV.NET.AFTER_DRAWS", 600,
         professional_comment="Puente gerencial después de aportes y retiros. No debe llamarse profit contable."),
    spec("Overview", "Posición operativa", "Caja validada total", "BS.CASH.TOTAL", 700,
         professional_comment="Caja solo si existe fuente frontend-safe. Si no, corresponde s/d y no cero."),
    spec("Overview", "Posición operativa", "Deuda total abierta", "ID.DEBT.TOTAL.OPEN", 800,
         professional_comment="Stock de deuda interna abierta por moneda. No es gasto operativo."),
    spec("Overview", "Posición operativa", "Principal abierto", "ID.DEBT.PRINCIPAL.OPEN", 810,
         professional_comment="Componente principal de deuda abierta."),
    spec("Overview", "Posición operativa", "Interés abierto", "ID.DEBT.INTEREST.OPEN", 820,
         professional_comment="Componente interés/costo de oportunidad si el engine lo produce."),
]

overview_table = build_statement_table(metrics, overview_specs, years, include_debug_cols=False, drop_all_empty_years=False)

# Presentation-layer ratios for ARS where relevant.
overview_table = add_ratio_row(
    overview_table,
    section="Resultado operativo",
    line="Margen operativo",
    numerator_line_contains="Resultado operativo neto",
    denominator_line_contains="Renta total",
    years=years,
    currency="ARS",
    professional_comment="Resultado operativo neto / renta total. Ratio de presentación."
)
overview_table = add_ratio_row(
    overview_table,
    section="Resultado operativo",
    line="OPEX / renta",
    numerator_line_contains="OPEX propiedad",
    denominator_line_contains="Renta total",
    years=years,
    currency="ARS",
    professional_comment="OPEX propiedad / renta total. Ratio de presión operativa."
)
overview_table = add_ratio_row(
    overview_table,
    section="Funding y distribuciones",
    line="Retiros / resultado operativo",
    numerator_line_contains="Retiros / gasto personal",
    denominator_line_contains="Resultado operativo neto",
    years=years,
    currency="ARS",
    professional_comment="Retiros personales sobre resultado operativo. Si supera 100%, la operación no cubre retiros."
)

displayed_overview = display_statement(
    overview_table,
    "Overview anual",
    "Resumen ejecutivo de operación, funding/distribuciones, posición y deuda. Monedas integradas por fila, sin totales cross-currency.",
)
export_table(overview_table, repo_root, "overview_balance_dashboard.csv")

## Overview anual

Resumen ejecutivo de operación, funding/distribuciones, posición y deuda. Monedas integradas por fila, sin totales cross-currency.

wrote: /home/matias/repos/accounting-backend/out/professional_pack/latest/tables/overview_balance_dashboard.csv rows=21 cols=12

PosixPath('/home/matias/repos/accounting-backend/out/professional_pack/latest/tables/overview_balance_dashboard.csv')

In [ ]:
def bridge_reconciliation(metrics, years, currency="ARS"):
    def series(metric_id):
        x = metrics[
            metrics["metric_id"].astype(str).eq(metric_id)
            & metrics["Currency"].astype(str).eq(currency)
        ].copy()
        return (
            x.groupby("period")["value"]
            .sum()
            .reindex(years)
            .astype(float)
        )

    operating = series("IS.NET.OPERATING")
    funding = series("FUND.CONTRIB.TOTAL")
    draws = series("DIST.DRAWS.PERSONAL")
    coverage = series("COV.NET.AFTER_DRAWS")


    residual = operating + funding - draws - coverage

    out = pd.DataFrame({
        "line": [
            "Resultado operativo",
            "+ Funding / aportes",
            "- Retiros y distribuciones totales",
            "= Cobertura después de funding y retiros",
            "Residual de reconciliación",
        ],
        "Currency": currency,
        **{
            y: [
                operating.get(y),
                funding.get(y),
                -draws.get(y),
                coverage.get(y),
                residual.get(y),
            ]
            for y in years
        }
    })

    return out


bridge_ars = bridge_reconciliation(metrics, years, "ARS")
display_statement(
    bridge_ars,
    "Reconciliación del puente de fondos — ARS",
    "Chequea que resultado + funding - retiros = cobertura. El residual debería ser cero o casi cero."
)
export_table(bridge_ars, repo_root, "overview_funds_bridge_reconciliation_ars.csv")

## Reconciliación del puente de fondos — ARS

Chequea que resultado + funding - retiros = cobertura. El residual debería ser cero o casi cero.

wrote: /home/matias/repos/accounting-backend/out/professional_pack/latest/tables/overview_funds_bridge_reconciliation_ars.csv rows=5 cols=7

PosixPath('/home/matias/repos/accounting-backend/out/professional_pack/latest/tables/overview_funds_bridge_reconciliation_ars.csv')

In [ ]:
def load_monthly_semantic(repo_root):
    path = repo_root / "out" / "run" / "accounting" / "latest" / "monthly_flow_semantic_split.csv"
    if not path.exists():
        print("Missing:", path)
        return pd.DataFrame()
    return pd.read_csv(path)


flow = load_monthly_semantic(repo_root)
print(flow.shape)
display(pd.DataFrame({"columns": flow.columns}))

(781, 25)

                      columns
0                      period
1                  period_end
2                    Currency
3                         Box
4                       Lugar
5                       actor
6                counterparty
7                       payer
8                    receiver
9                     channel
10                  cash_path
11            semantic_bucket
12         semantic_subbucket
13                  amount_in
14                 amount_out
15                 net_amount
16                 amount_abs
17                       n_tx
18      classification_status
19  classification_confidence
20            review_required
21               source_table
22       source_tx_ids_sample
23                   rule_ids
24                      notes

In [ ]:
def normalize_period_year(df):
    x = df.copy()
    if "period" in x.columns:
        x["year"] = x["period"].astype(str).str.slice(0, 4)
    elif "month" in x.columns:
        x["year"] = x["month"].astype(str).str.slice(0, 4)
    elif "Fecha" in x.columns:
        x["year"] = pd.to_datetime(x["Fecha"], errors="coerce").dt.year.astype("Int64").astype(str)
    else:
        x["year"] = ""
    return x


flow2 = normalize_period_year(flow)

value_col = "value" if "value" in flow2.columns else None
if value_col is None:
    for c in ["amount", "Amount", "monto", "Monto", "signed_amount"]:
        if c in flow2.columns:
            value_col = c
            break

# if value_col is None:
#     raise ValueError("Could not find value column in monthly_flow_semantic_split")

# flow2[value_col] = pd.to_numeric(flow2[value_col], errors="coerce")

cols_to_show = [
    c for c in [
        "year",
        "period",
        "Currency",
        "Box",
        "box",
        "governance_box",
        "payer",
        "receiver",
        "actor",
        "counterparty",
        "semantic_bucket",
        "semantic_subbucket",
        "cash_path",
        "flow_type",
        "Tipo",
        "source_table",
        value_col,
    ]
    if c in flow2.columns
]

f2024 = flow2[
    (flow2["year"] == "2024").astype(bool)
    & flow2.get("Currency", pd.Series("", index=flow2.index)).astype(str).eq("ARS")
].copy()

display(f2024[cols_to_show].head(100))

     year   period Currency                  Box  payer   receiver                actor counterparty              semantic_bucket             semantic_subbucket                    cash_path          source_table
221  2024  2024-01      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
222  2024  2024-01      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
223  2024  2024-01      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
224  2024  2024-01      ARS      Family Business     FB      Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
225  2024  2024-01      ARS            Household     MI         HH            Household           MI         funding_contribution  family_or_tenant_contribution  Contribucion:Contribuciones  ledger_canonical.csv
226  2024  2024-01      ARS            Household     HH  Servicios            Household    Servicios                property_opex                       services               Pagos:Servicio  ledger_canonical.csv
227  2024  2024-01      ARS  Property Management     PM     Costos  Property Management       Costos                property_opex                          legal                  Pagos:Legal  ledger_canonical.csv
228  2024  2024-01      ARS  Property Management     MI         PM  Property Management           MI                property_opex                          legal           Contribucion:Legal  ledger_canonical.csv
229  2024  2024-02      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
230  2024  2024-02      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
231  2024  2024-02      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
232  2024  2024-02      ARS      Family Business     FB      Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
233  2024  2024-02      ARS            Household  Cande         HH            Household        Cande                property_opex                       services        Contribucion:Servicio  ledger_canonical.csv
234  2024  2024-02      ARS            Household     MI         HH            Household           MI         funding_contribution  family_or_tenant_contribution  Contribucion:Contribuciones  ledger_canonical.csv
235  2024  2024-02      ARS            Household     HH  Servicios            Household    Servicios                property_opex                       services               Pagos:Servicio  ledger_canonical.csv
236  2024  2024-03      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
237  2024  2024-03      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
238  2024  2024-03      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
239  2024  2024-03      ARS      Family Business     FB      Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
240  2024  2024-03      ARS            Household  Cande         HH            Household        Cande                property_opex                       services        Contribucion:Servicio  ledger_canonical.csv
241  2024  2024-03      ARS            Household     MI         HH            Household           MI         funding_contribution  family_or_tenant_contribution  Contribucion:Contribuciones  ledger_canonical.csv
242  2024  2024-03      ARS            Household     HH  Servicios            Household    Servicios                property_opex                       services               Pagos:Servicio  ledger_canonical.csv
244  2024  2024-04      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
245  2024  2024-04      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
246  2024  2024-04      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
247  2024  2024-04      ARS      Family Business     FB      Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
248  2024  2024-04      ARS            Household     HH     Costos            Household       Costos                property_opex                    maintenance          Pagos:Mantenimiento  ledger_canonical.csv
249  2024  2024-04      ARS            Household     MI         HH            Household           MI         funding_contribution  family_or_tenant_contribution  Contribucion:Contribuciones  ledger_canonical.csv
250  2024  2024-04      ARS            Household     HH  Servicios            Household    Servicios                property_opex                       services               Pagos:Servicio  ledger_canonical.csv
251  2024  2024-04      ARS  Property Management     PM  Impuestos  Property Management    Impuestos                property_opex                          taxes              Pagos:Impuestos  ledger_canonical.csv
252  2024  2024-04      ARS  Property Management     MI         PM  Property Management           MI                property_opex                          taxes       Contribucion:Impuestos  ledger_canonical.csv
253  2024  2024-04      ARS  Property Management     MI         PM  Property Management           MI                property_opex                       services        Contribucion:Servicio  ledger_canonical.csv
254  2024  2024-04      ARS  Property Management     PM  Servicios  Property Management    Servicios                property_opex                       services               Pagos:Servicio  ledger_canonical.csv
255  2024  2024-04      ARS  Property Management     PM     Costos  Property Management       Costos                property_opex                          legal                  Pagos:Legal  ledger_canonical.csv
256  2024  2024-04      ARS  Property Management     MI         PM  Property Management           MI                property_opex                          legal           Contribucion:Legal  ledger_canonical.csv
257  2024  2024-04      ARS  Property Management     PM  Impuestos  Property Management    Impuestos                property_opex                          taxes              Pagos:Impuestos  ledger_canonical.csv
258  2024  2024-04      ARS  Property Management     FX         PM  Property Management           FX                  treasury_fx         fx_conversion_proceeds                    Cambio:FX  ledger_canonical.csv
259  2024  2024-04      ARS  Property Management     MI  Alejandro  Property Management           MI                debt_movement                      principal            Transfer:Prestamo  ledger_canonical.csv
260  2024  2024-04      ARS  Property Management     PM         MI  Property Management           MI                debt_movement                      repayment              Transfer:Repago  ledger_canonical.csv
263  2024  2024-05      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
264  2024  2024-05      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
265  2024  2024-05      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
266  2024  2024-05      ARS      Family Business     FB      Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
267  2024  2024-05      ARS            Household     MI         HH            Household           MI         funding_contribution  family_or_tenant_contribution  Contribucion:Contribuciones  ledger_canonical.csv
268  2024  2024-05      ARS            Household     HH  Servicios            Household    Servicios                property_opex                       services               Pagos:Servicio  ledger_canonical.csv
269  2024  2024-05      ARS  Property Management    Inq  Impuestos  Property Management    Impuestos                property_opex                          taxes              Pagos:Impuestos  ledger_canonical.csv
270  2024  2024-05      ARS  Property Management    Inq  Impuestos  Property Management    Impuestos                property_opex                          taxes              Pagos:Impuestos  ledger_canonical.csv
271  2024  2024-05      ARS  Property Management    Inq  Impuestos  Property Management    Impuestos                property_opex                          taxes              Pagos:Impuestos  ledger_canonical.csv
272  2024  2024-05      ARS  Property Management     PM  Impuestos  Property Management    Impuestos                property_opex                          taxes              Pagos:Impuestos  ledger_canonical.csv
273  2024  2024-05      ARS  Property Management     MI         PM  Property Management           MI                property_opex                          taxes       Contribucion:Impuestos  ledger_canonical.csv
274  2024  2024-05      ARS  Property Management     MI         PM  Property Management           MI                property_opex                       services        Contribucion:Servicio  ledger_canonical.csv
275  2024  2024-05      ARS  Property Management     PM  Servicios  Property Management    Servicios                property_opex                       services               Pagos:Servicio  ledger_canonical.csv
276  2024  2024-05      ARS  Property Management     FX         PM  Property Management           FX                  treasury_fx         fx_conversion_proceeds                    Cambio:FX  ledger_canonical.csv
277  2024  2024-05      ARS  Property Management     MI  Alejandro  Property Management           MI                debt_movement                      principal            Transfer:Prestamo  ledger_canonical.csv
280  2024  2024-06      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
281  2024  2024-06      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
282  2024  2024-06      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
283  2024  2024-06      ARS      Family Business     FB      Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
284  2024  2024-06      ARS            Household   Alen         HH            Household         Alen         funding_contribution  family_or_tenant_contribution  Contribucion:Contribuciones  ledger_canonical.csv
285  2024  2024-06      ARS            Household     HH         MI            Household           MI                debt_movement                      repayment              Transfer:Repago  ledger_canonical.csv
286  2024  2024-06      ARS            Household     MI         HH            Household           MI         funding_contribution  family_or_tenant_contribution  Contribucion:Contribuciones  ledger_canonical.csv
287  2024  2024-06      ARS            Household     HH  Servicios            Household    Servicios                property_opex                       services               Pagos:Servicio  ledger_canonical.csv
288  2024  2024-06      ARS  Property Management    Inq  Impuestos  Property Management    Impuestos                property_opex                          taxes              Pagos:Impuestos  ledger_canonical.csv
289  2024  2024-06      ARS  Property Management     MI         PM  Property Management           MI                property_opex                       services        Contribucion:Servicio  ledger_canonical.csv
290  2024  2024-06      ARS  Property Management     PM  Servicios  Property Management    Servicios                property_opex                       services               Pagos:Servicio  ledger_canonical.csv
291  2024  2024-06      ARS  Property Management     PM  Impuestos  Property Management    Impuestos                property_opex                          taxes              Pagos:Impuestos  ledger_canonical.csv
292  2024  2024-06      ARS  Property Management    Inq         FB  Property Management          Inq         funding_contribution  family_or_tenant_contribution  Contribucion:Contribuciones  ledger_canonical.csv
293  2024  2024-06      ARS  Property Management     MI         PM  Property Management           MI                property_opex                          taxes       Contribucion:Impuestos  ledger_canonical.csv
294  2024  2024-06      ARS  Property Management     PM  Impuestos  Property Management    Impuestos                property_opex                          taxes              Pagos:Impuestos  ledger_canonical.csv
295  2024  2024-06      ARS  Property Management     MI         PM  Property Management           MI                property_opex                          taxes       Contribucion:Impuestos  ledger_canonical.csv
296  2024  2024-06      ARS  Property Management    Inq  Impuestos  Property Management    Impuestos                property_opex                          taxes              Pagos:Impuestos  ledger_canonical.csv
297  2024  2024-06      ARS  Property Management     PM  Impuestos  Property Management    Impuestos                property_opex                          taxes              Pagos:Impuestos  ledger_canonical.csv
298  2024  2024-06      ARS  Property Management     MI         PM  Property Management           MI                property_opex                          taxes       Contribucion:Impuestos  ledger_canonical.csv
299  2024  2024-06      ARS  Property Management    Inq  Impuestos  Property Management    Impuestos                property_opex                          taxes              Pagos:Impuestos  ledger_canonical.csv
300  2024  2024-06      ARS  Property Management     PM  Impuestos  Property Management    Impuestos                property_opex                          taxes              Pagos:Impuestos  ledger_canonical.csv
301  2024  2024-06      ARS  Property Management     MI         PM  Property Management           MI                property_opex                          taxes       Contribucion:Impuestos  ledger_canonical.csv
302  2024  2024-06      ARS  Property Management     PM  Impuestos  Property Management    Impuestos                property_opex                          taxes              Pagos:Impuestos  ledger_canonical.csv
303  2024  2024-06      ARS  Property Management     MI         PM  Property Management           MI                property_opex                          taxes       Contribucion:Impuestos  ledger_canonical.csv
304  2024  2024-06      ARS  Property Management     FX         PM  Property Management           FX                  treasury_fx         fx_conversion_proceeds                    Cambio:FX  ledger_canonical.csv
305  2024  2024-06      ARS  Property Management     PM         MI  Property Management           MI                debt_movement                      repayment              Transfer:Repago  ledger_canonical.csv
308  2024  2024-07      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
309  2024  2024-07      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
310  2024  2024-07      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
311  2024  2024-07      ARS      Family Business     FB      Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
312  2024  2024-07      ARS            Household     HH     Costos            Household       Costos                property_opex                    maintenance          Pagos:Mantenimiento  ledger_canonical.csv
313  2024  2024-07      ARS            Household     MI         HH            Household           MI         funding_contribution  family_or_tenant_contribution  Contribucion:Contribuciones  ledger_canonical.csv
314  2024  2024-07      ARS            Household     HH  Servicios            Household    Servicios                property_opex                       services               Pagos:Servicio  ledger_canonical.csv
315  2024  2024-07      ARS  Property Management    Inq  Impuestos  Property Management    Impuestos                property_opex                          taxes              Pagos:Impuestos  ledger_canonical.csv
316  2024  2024-07      ARS  Property Management    Inq  Impuestos  Property Management    Impuestos                property_opex                          taxes              Pagos:Impuestos  ledger_canonical.csv
317  2024  2024-07      ARS  Property Management    Inq         FB  Property Management          Inq         funding_contribution  family_or_tenant_contribution  Contribucion:Contribuciones  ledger_canonical.csv
318  2024  2024-07      ARS  Property Management     FX         PM  Property Management           FX                  treasury_fx         fx_conversion_proceeds                    Cambio:FX  ledger_canonical.csv
319  2024  2024-07      ARS  Property Management     PM         MI  Property Management           MI                debt_movement                      repayment              Transfer:Repago  ledger_canonical.csv
322  2024  2024-08      ARS      Family Business    Inq         FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv

In [ ]:
f2024.sample(20)

,period,period_end,Currency,Box,Lugar,actor,counterparty,payer,receiver,channel,cash_path,semantic_bucket,semantic_subbucket,amount_in,amount_out,net_amount,amount_abs,n_tx,classification_status,classification_confidence,review_required,source_table,source_tx_ids_sample,rule_ids,notes,year
367,2024-10,2024-10-31,ARS,Property Management,CABA,Property Management,Impuestos,PM,Impuestos,Property Management,Pagos:Impuestos,property_opex,taxes,0.0,119602.0,-119602.0,119602.0,1,classified,high,False,ledger_canonical.csv,388309d9d9f6d003,R002_property_taxes,NaN,2024
286,2024-06,2024-06-30,ARS,Household,CABA,Household,MI,MI,HH,Household,Contribucion:Contribuciones,funding_contribution,family_or_tenant_contribution,140000.0,0.0,140000.0,140000.0,1,classified,high,False,ledger_canonical.csv,881929a06cac7a64,R006_contribution,NaN,2024
420,2024-12,2024-12-31,ARS,Property Management,CABA,Property Management,MI,MI,PM,Property Management,Contribucion:Servicio,property_opex,services,452484.0,0.0,452484.0,452484.0,1,classified,high,False,ledger_canonical.csv,d87c53eb189ca5d9,R003_property_services,NaN,2024
260,2024-04,2024-04-30,ARS,Property Management,NaN,Property Management,MI,PM,MI,Property Management,Transfer:Repago,debt_movement,repayment,0.0,53243.0,-53243.0,53243.0,1,classified,high,False,ledger_canonical.csv,c72ff53df4c5f24b,R008_debt_repayment,NaN,2024
224,2024-01,2024-01-31,ARS,Family Business,NaN,Family Business,Gasto,FB,Gasto,Family Business,Transfer:Gasto,family_withdrawal_candidate,personal_expense,0.0,765890.0,-765890.0,765890.0,1,classified,medium,False,ledger_canonical.csv,a6fd814ecb2d2843,R011_personal_expense_text,review family/informal withdrawal candidate,2024
336,2024-09,2024-09-30,ARS,Family Business,Tigre 01,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,516127.0,0.0,516127.0,516127.0,3,classified,high,False,ledger_canonical.csv,a38d5fdbb0bf95dd;a2bbe396e76b45f6;5bdc888afdd4...,R001_rent_collections,NaN,2024
359,2024-10,2024-10-31,ARS,Household,CABA,Household,Alen,Alen,HH,Household,Contribucion:Contribuciones,funding_contribution,family_or_tenant_contribution,150000.0,0.0,150000.0,150000.0,1,classified,high,False,ledger_canonical.csv,4ffbbea35a9c617a,R006_contribution,NaN,2024
265,2024-05,2024-05-31,ARS,Family Business,Tigre 32,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,342556.0,0.0,342556.0,342556.0,3,classified,high,False,ledger_canonical.csv,5609904d55a476d3;c1633aa18d6aacda;b03053f0715f...,R001_rent_collections,NaN,2024
327,2024-08,2024-08-31,ARS,Household,CABA,Household,Cande,Cande,HH,Household,Contribucion:Servicio,property_opex,services,35500.0,0.0,35500.0,35500.0,1,classified,high,False,ledger_canonical.csv,d944b9acfebdabd1,R003_property_services,NaN,2024
423,2024-12,2024-12-31,ARS,Property Management,Tigre 01,Property Management,Impuestos,PM,Impuestos,Property Management,Pagos:Impuestos,property_opex,taxes,0.0,147638.0,-147638.0,147638.0,1,classified,high,False,ledger_canonical.csv,2a67de1891c84ee6,R002_property_taxes,NaN,2024
314,2024-07,2024-07-31,ARS,Household,CABA,Household,Servicios,HH,Servicios,Household,Pagos:Servicio,property_opex,services,0.0,14952.0,-14952.0,14952.0,1,classified,high,False,ledger_canonical.csv,ac2c22a2b45d73b8,R003_property_services,NaN,2024
276,2024-05,2024-05-31,ARS,Property Management,NaN,Property Management,FX,FX,PM,Property Management,Cambio:FX,treasury_fx,fx_conversion_proceeds,410000.0,0.0,410000.0,410000.0,1,classified,high,False,ledger_canonical.csv,a86e38d2bac5f0ee,R014_fx_conversion_proceeds,"FX conversion proceeds; not revenue, not fundi...",2024
430,2024-12,2024-12-31,ARS,Property Management,Tigre 28,Property Management,Inq,Inq,PM,Property Management,Contribucion:Impuestos,property_opex,taxes,34527.0,0.0,34527.0,34527.0,1,classified,high,False,ledger_canonical.csv,cf163b82b9346a85,R002_property_taxes,NaN,2024
269,2024-05,2024-05-31,ARS,Property Management,CABA,Property Management,Impuestos,Inq,Impuestos,Property Management,Pagos:Impuestos,property_opex,taxes,0.0,65000.0,-65000.0,65000.0,1,classified,high,False,ledger_canonical.csv,b9314b6eb5dd530e,R002_property_taxes,NaN,2024
304,2024-06,2024-06-30,ARS,Property Management,NaN,Property Management,FX,FX,PM,Property Management,Cambio:FX,treasury_fx,fx_conversion_proceeds,156000.0,0.0,156000.0,156000.0,1,classified,high,False,ledger_canonical.csv,29f71e8468f8c7e6,R014_fx_conversion_proceeds,"FX conversion proceeds; not revenue, not fundi...",2024
291,2024-06,2024-06-30,ARS,Property Management,Tigre 01,Property Management,Impuestos,PM,Impuestos,Property Management,Pagos:Impuestos,property_opex,taxes,0.0,42591.0,-42591.0,42591.0,1,classified,high,False,ledger_canonical.csv,115e62e0c29af989,R002_property_taxes,NaN,2024
398,2024-11,2024-11-30,ARS,Property Management,Tigre 01,Property Management,Impuestos,PM,Impuestos,Property Management,Pagos:Impuestos,property_opex,taxes,0.0,35000.0,-35000.0,35000.0,1,classified,high,False,ledger_canonical.csv,8b9c01843efcffc5,R002_property_taxes,NaN,2024
387,2024-11,2024-11-30,ARS,Family Business,Tigre 28,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,370000.0,0.0,370000.0,370000.0,2,classified,high,False,ledger_canonical.csv,aed940a322ac1744;58f8c6565da79175,R001_rent_collections,NaN,2024
284,2024-06,2024-06-30,ARS,Household,CABA,Household,Alen,Alen,HH,Household,Contribucion:Contribuciones,funding_contribution,family_or_tenant_contribution,70000.0,0.0,70000.0,70000.0,1,classified,high,False,ledger_canonical.csv,75a12bbda00538b8,R006_contribution,NaN,2024
374,2024-10,2024-10-31,ARS,Property Management,Tigre 02,Property Management,MI,MI,PM,Property Management,Contribucion:Impuestos,property_opex,taxes,16387.0,0.0,16387.0,16387.0,1,classified,high,False,ledger_canonical.csv,a1cfdba98b2cba5d,R002_property_taxes,NaN,2024

In [8]:
fb_cols = [c for c in ["Box", "box", "governance_box", "payer", "receiver", "actor", "counterparty"] if c in f2024.columns]

mask_fb = pd.Series(False, index=f2024.index)
for c in fb_cols:
    mask_fb = mask_fb | f2024[c].astype(str).str.contains("Family Business|FB", case=False, na=False)

fb2024 = f2024[mask_fb].copy()

print("FB-related 2024 rows:", len(fb2024))
display(fb2024[cols_to_show].sort_values([c for c in ["period", "semantic_bucket", "semantic_subbucket"] if c in fb2024.columns]).head(200))

FB-related 2024 rows: 51

     year   period Currency                  Box payer receiver                actor counterparty              semantic_bucket             semantic_subbucket                    cash_path          source_table
224  2024  2024-01      ARS      Family Business    FB    Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
221  2024  2024-01      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
222  2024  2024-01      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
223  2024  2024-01      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
232  2024  2024-02      ARS      Family Business    FB    Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
229  2024  2024-02      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
230  2024  2024-02      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
231  2024  2024-02      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
239  2024  2024-03      ARS      Family Business    FB    Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
236  2024  2024-03      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
237  2024  2024-03      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
238  2024  2024-03      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
247  2024  2024-04      ARS      Family Business    FB    Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
244  2024  2024-04      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
245  2024  2024-04      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
246  2024  2024-04      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
266  2024  2024-05      ARS      Family Business    FB    Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
263  2024  2024-05      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
264  2024  2024-05      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
265  2024  2024-05      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
283  2024  2024-06      ARS      Family Business    FB    Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
292  2024  2024-06      ARS  Property Management   Inq       FB  Property Management          Inq         funding_contribution  family_or_tenant_contribution  Contribucion:Contribuciones  ledger_canonical.csv
280  2024  2024-06      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
281  2024  2024-06      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
282  2024  2024-06      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
311  2024  2024-07      ARS      Family Business    FB    Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
317  2024  2024-07      ARS  Property Management   Inq       FB  Property Management          Inq         funding_contribution  family_or_tenant_contribution  Contribucion:Contribuciones  ledger_canonical.csv
308  2024  2024-07      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
309  2024  2024-07      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
310  2024  2024-07      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
325  2024  2024-08      ARS      Family Business    FB    Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
332  2024  2024-08      ARS  Property Management   Inq       FB  Property Management          Inq         funding_contribution  family_or_tenant_contribution  Contribucion:Contribuciones  ledger_canonical.csv
322  2024  2024-08      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
323  2024  2024-08      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
324  2024  2024-08      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
339  2024  2024-09      ARS      Family Business    FB    Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
336  2024  2024-09      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
337  2024  2024-09      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
338  2024  2024-09      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
358  2024  2024-10      ARS      Family Business    FB    Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
355  2024  2024-10      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
356  2024  2024-10      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
357  2024  2024-10      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
389  2024  2024-11      ARS      Family Business    FB    Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
386  2024  2024-11      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
387  2024  2024-11      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
388  2024  2024-11      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
410  2024  2024-12      ARS      Family Business    FB    Gasto      Family Business        Gasto  family_withdrawal_candidate               personal_expense               Transfer:Gasto  ledger_canonical.csv
407  2024  2024-12      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
408  2024  2024-12      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv
409  2024  2024-12      ARS      Family Business   Inq       FB      Family Business          Inq            operating_revenue                           rent                 Cobros:Renta  ledger_canonical.csv

In [ ]:
fb2024.sort_values([c for c in ["period", "semantic_bucket", "semantic_subbucket"] if c in fb2024.columns])

,period,period_end,Currency,Box,Lugar,actor,counterparty,payer,receiver,channel,cash_path,semantic_bucket,semantic_subbucket,amount_in,amount_out,net_amount,amount_abs,n_tx,classification_status,classification_confidence,review_required,source_table,source_tx_ids_sample,rule_ids,notes,year
224,2024-01,2024-01-31,ARS,Family Business,NaN,Family Business,Gasto,FB,Gasto,Family Business,Transfer:Gasto,family_withdrawal_candidate,personal_expense,0.0,765890.0,-765890.0,765890.0,1,classified,medium,False,ledger_canonical.csv,a6fd814ecb2d2843,R011_personal_expense_text,review family/informal withdrawal candidate,2024
221,2024-01,2024-01-31,ARS,Family Business,Tigre 01,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,367823.0,0.0,367823.0,367823.0,3,classified,high,False,ledger_canonical.csv,254f6f0a8633a959;d47323313841de72;73681a97dc10...,R001_rent_collections,NaN,2024
222,2024-01,2024-01-31,ARS,Family Business,Tigre 28,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,229322.0,0.0,229322.0,229322.0,2,classified,high,False,ledger_canonical.csv,6b9525b7f4c457b5;ebda5d099d229953,R001_rent_collections,NaN,2024
223,2024-01,2024-01-31,ARS,Family Business,Tigre 32,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,168745.0,0.0,168745.0,168745.0,2,classified,high,False,ledger_canonical.csv,4953edf8f1d97f1a;25d8294653a4cd19,R001_rent_collections,NaN,2024
232,2024-02,2024-02-29,ARS,Family Business,NaN,Family Business,Gasto,FB,Gasto,Family Business,Transfer:Gasto,family_withdrawal_candidate,personal_expense,0.0,883490.0,-883490.0,883490.0,1,classified,medium,False,ledger_canonical.csv,e735684fbe3ed901,R011_personal_expense_text,review family/informal withdrawal candidate,2024
229,2024-02,2024-02-29,ARS,Family Business,Tigre 01,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,385423.0,0.0,385423.0,385423.0,3,classified,high,False,ledger_canonical.csv,be28e81ce6388076;f4941495cf33cd95;8f4623d48142...,R001_rent_collections,NaN,2024
230,2024-02,2024-02-29,ARS,Family Business,Tigre 28,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,229322.0,0.0,229322.0,229322.0,2,classified,high,False,ledger_canonical.csv,920af0a7f85e89d4;88d1c989bcff5d05,R001_rent_collections,NaN,2024
231,2024-02,2024-02-29,ARS,Family Business,Tigre 32,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,268745.0,0.0,268745.0,268745.0,3,classified,high,False,ledger_canonical.csv,960425489a0a731f;ba48284b16fb0974;182b0e0439c1...,R001_rent_collections,NaN,2024
239,2024-03,2024-03-31,ARS,Family Business,NaN,Family Business,Gasto,FB,Gasto,Family Business,Transfer:Gasto,family_withdrawal_candidate,personal_expense,0.0,883490.0,-883490.0,883490.0,1,classified,medium,False,ledger_canonical.csv,226b8b61bca047a6,R011_personal_expense_text,review family/informal withdrawal candidate,2024
236,2024-03,2024-03-31,ARS,Family Business,Tigre 01,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,385423.0,0.0,385423.0,385423.0,3,classified,high,False,ledger_canonical.csv,e1e5ce87a85b1fce;5ec1016e4d42841f;185747f34db9...,R001_rent_collections,NaN,2024
237,2024-03,2024-03-31,ARS,Family Business,Tigre 28,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,229322.0,0.0,229322.0,229322.0,2,classified,high,False,ledger_canonical.csv,b8ba471deee683dc;8c44c97cb49b2f1d,R001_rent_collections,NaN,2024
238,2024-03,2024-03-31,ARS,Family Business,Tigre 32,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,268745.0,0.0,268745.0,268745.0,3,classified,high,False,ledger_canonical.csv,730e5de98befc72e;4ab49c400489bb8b;2b26309f6885...,R001_rent_collections,NaN,2024
247,2024-04,2024-04-30,ARS,Family Business,NaN,Family Business,Gasto,FB,Gasto,Family Business,Transfer:Gasto,family_withdrawal_candidate,personal_expense,0.0,1086449.0,-1086449.0,1086449.0,1,classified,medium,False,ledger_canonical.csv,0c99d1752a7fa6fe,R011_personal_expense_text,review family/informal withdrawal candidate,2024
244,2024-04,2024-04-30,ARS,Family Business,Tigre 01,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,464027.0,0.0,464027.0,464027.0,3,classified,high,False,ledger_canonical.csv,d762ccc011b2735f;b67201a2ba726b78;495330639c32...,R001_rent_collections,NaN,2024
245,2024-04,2024-04-30,ARS,Family Business,Tigre 28,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,279866.0,0.0,279866.0,279866.0,2,classified,high,False,ledger_canonical.csv,e97ec65b17567e95;3148a94c7a4ed025,R001_rent_collections,NaN,2024
246,2024-04,2024-04-30,ARS,Family Business,Tigre 32,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,342556.0,0.0,342556.0,342556.0,3,classified,high,False,ledger_canonical.csv,7ed82b6b3afa076d;265839a31d7cc38b;b5c4e08ba49a...,R001_rent_collections,NaN,2024
266,2024-05,2024-05-31,ARS,Family Business,NaN,Family Business,Gasto,FB,Gasto,Family Business,Transfer:Gasto,family_withdrawal_candidate,personal_expense,0.0,1086449.0,-1086449.0,1086449.0,1,classified,medium,False,ledger_canonical.csv,da7328ce0d1c9a8a,R011_personal_expense_text,review family/informal withdrawal candidate,2024
263,2024-05,2024-05-31,ARS,Family Business,Tigre 01,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,464027.0,0.0,464027.0,464027.0,3,classified,high,False,ledger_canonical.csv,cb6ec67df9fe8831;ed1bf29eab85631f;02421e432ca2...,R001_rent_collections,NaN,2024
264,2024-05,2024-05-31,ARS,Family Business,Tigre 28,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,279866.0,0.0,279866.0,279866.0,2,classified,high,False,ledger_canonical.csv,30d86a04eec1d59e;907d00c469ec6f2c,R001_rent_collections,NaN,2024
265,2024-05,2024-05-31,ARS,Family Business,Tigre 32,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,342556.0,0.0,342556.0,342556.0,3,classified,high,False,ledger_canonical.csv,5609904d55a476d3;c1633aa18d6aacda;b03053f0715f...,R001_rent_collections,NaN,2024
283,2024-06,2024-06-30,ARS,Family Business,NaN,Family Business,Gasto,FB,Gasto,Family Business,Transfer:Gasto,family_withdrawal_candidate,personal_expense,0.0,1086449.0,-1086449.0,1086449.0,1,classified,medium,False,ledger_canonical.csv,790bbc1353d9bc94,R011_personal_expense_text,review family/informal withdrawal candidate,2024
292,2024-06,2024-06-30,ARS,Property Management,Tigre 01,Property Management,Inq,Inq,FB,Property Management,Contribucion:Contribuciones,funding_contribution,family_or_tenant_contribution,50000.0,0.0,50000.0,50000.0,1,classified,high,False,ledger_canonical.csv,db7f77533dc4942b,R006_contribution,NaN,2024
280,2024-06,2024-06-30,ARS,Family Business,Tigre 01,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,464027.0,0.0,464027.0,464027.0,3,classified,high,False,ledger_canonical.csv,15d61f749c252f77;574a9a9fb3625198;189d496d8dbb...,R001_rent_collections,NaN,2024
281,2024-06,2024-06-30,ARS,Family Business,Tigre 28,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,279866.0,0.0,279866.0,279866.0,2,classified,high,False,ledger_canonical.csv,3d2326744f7dcde1;5c1afcae121c1835,R001_rent_collections,NaN,2024
282,2024-06,2024-06-30,ARS,Family Business,Tigre 32,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,342556.0,0.0,342556.0,342556.0,3,classified,high,False,ledger_canonical.csv,1521a759de4e4805;bc15b398372f59b0;4926b7232799...,R001_rent_collections,NaN,2024
311,2024-07,2024-07-31,ARS,Family Business,NaN,Family Business,Gasto,FB,Gasto,Family Business,Transfer:Gasto,family_withdrawal_candidate,personal_expense,0.0,1086449.0,-1086449.0,1086449.0,1,classified,medium,False,ledger_canonical.csv,1e621e1b11b6a53a,R011_personal_expense_text,review family/informal withdrawal candidate,2024
317,2024-07,2024-07-31,ARS,Property Management,Tigre 01,Property Management,Inq,Inq,FB,Property Management,Contribucion:Contribuciones,funding_contribution,family_or_tenant_contribution,50000.0,0.0,50000.0,50000.0,1,classified,high,False,ledger_canonical.csv,389cb6d4b74e3137,R006_contribution,NaN,2024
308,2024-07,2024-07-31,ARS,Family Business,Tigre 01,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,464027.0,0.0,464027.0,464027.0,3,classified,high,False,ledger_canonical.csv,f5437dd312e48a19;d91cdb2204e0660e;557016f2880b...,R001_rent_collections,NaN,2024
309,2024-07,2024-07-31,ARS,Family Business,Tigre 28,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,279866.0,0.0,279866.0,279866.0,2,classified,high,False,ledger_canonical.csv,08264fec3aec24e7;b6dc342e43ebe2d2,R001_rent_collections,NaN,2024
310,2024-07,2024-07-31,ARS,Family Business,Tigre 32,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,342556.0,0.0,342556.0,342556.0,3,classified,high,False,ledger_canonical.csv,116403e36964cf82;82149eaa21e86665;6092f57f3ee0...,R001_rent_collections,NaN,2024
325,2024-08,2024-08-31,ARS,Family Business,NaN,Family Business,Gasto,FB,Gasto,Family Business,Transfer:Gasto,family_withdrawal_candidate,personal_expense,0.0,1138549.0,-1138549.0,1138549.0,1,classified,medium,False,ledger_canonical.csv,83ec191842188e84,R011_personal_expense_text,review family/informal withdrawal candidate,2024
332,2024-08,2024-08-31,ARS,Property Management,Tigre 01,Property Management,Inq,Inq,FB,Property Management,Contribucion:Contribuciones,funding_contribution,family_or_tenant_contribution,50000.0,0.0,50000.0,50000.0,1,classified,high,False,ledger_canonical.csv,8d152bc5fe2b2889,R006_contribution,NaN,2024
322,2024-08,2024-08-31,ARS,Family Business,Tigre 01,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,516127.0,0.0,516127.0,516127.0,3,classified,high,False,ledger_canonical.csv,990fe0f0b0876bb7;602206f47499f65f;5ca9a24c23de...,R001_rent_collections,NaN,2024
323,2024-08,2024-08-31,ARS,Family Business,Tigre 28,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,279866.0,0.0,279866.0,279866.0,2,classified,high,False,ledger_canonical.csv,a365c79eb7187a86;2423e4bfa1053ae0,R001_rent_collections,NaN,2024
324,2024-08,2024-08-31,ARS,Family Business,Tigre 32,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,342556.0,0.0,342556.0,342556.0,3,classified,high,False,ledger_canonical.csv,d8f2679ab972dcfa;5ab143035182f6f3;82dcf8daf883...,R001_rent_collections,NaN,2024
339,2024-09,2024-09-30,ARS,Family Business,NaN,Family Business,Gasto,FB,Gasto,Family Business,Transfer:Gasto,family_withdrawal_candidate,personal_expense,0.0,1138549.0,-1138549.0,1138549.0,1,classified,medium,False,ledger_canonical.csv,5932def6b276859e,R011_personal_expense_text,review family/informal withdrawal candidate,2024
336,2024-09,2024-09-30,ARS,Family Business,Tigre 01,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,516127.0,0.0,516127.0,516127.0,3,classified,high,False,ledger_canonical.csv,a38d5fdbb0bf95dd;a2bbe396e76b45f6;5bdc888afdd4...,R001_rent_collections,NaN,2024
337,2024-09,2024-09-30,ARS,Family Business,Tigre 28,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,279866.0,0.0,279866.0,279866.0,2,classified,high,False,ledger_canonical.csv,984b6b0a5d299522;068252410c0ec7bb,R001_rent_collections,NaN,2024
338,2024-09,2024-09-30,ARS,Family Business,Tigre 32,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,342556.0,0.0,342556.0,342556.0,3,classified,high,False,ledger_canonical.csv,218a0e860d4b8de4;4d8dd2dab4ed00c4;b44e2306b188...,R001_rent_collections,NaN,2024
358,2024-10,2024-10-31,ARS,Family Business,NaN,Family Business,Gasto,FB,Gasto,Family Business,Transfer:Gasto,family_withdrawal_candidate,personal_expense,0.0,1467524.0,-1467524.0,1467524.0,1,classified,medium,False,ledger_canonical.csv,ce115e68b034c637,R011_personal_expense_text,review family/informal withdrawal candidate,2024
355,2024-10,2024-10-31,ARS,Family Business,Tigre 01,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,649574.0,0.0,649574.0,649574.0,3,classified,high,False,ledger_canonical.csv,4dd202fc2858e78a;55fa5c683a0ac31e;4b2de7db3567...,R001_rent_collections,NaN,2024
356,2024-10,2024-10-31,ARS,Family Business,Tigre 28,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,370000.0,0.0,370000.0,370000.0,2,classified,high,False,ledger_canonical.csv,979c2646e05b9d95;05cb94a056d5d08b,R001_rent_collections,NaN,2024
357,2024-10,2024-10-31,ARS,Family Business,Tigre 32,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,447950.0,0.0,447950.0,447950.0,3,classified,high,False,ledger_canonical.csv,af4647a80d3e0865;bd95875f6a9b2fa1;542b97fa5f1a...,R001_rent_collections,NaN,2024
389,2024-11,2024-11-30,ARS,Family Business,NaN,Family Business,Gasto,FB,Gasto,Family Business,Transfer:Gasto,family_withdrawal_candidate,personal_expense,0.0,1467524.0,-1467524.0,1467524.0,1,classified,medium,False,ledger_canonical.csv,d07e9b4abea026be,R011_personal_expense_text,review family/informal withdrawal candidate,2024
386,2024-11,2024-11-30,ARS,Family Business,Tigre 01,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,649574.0,0.0,649574.0,649574.0,3,classified,high,False,ledger_canonical.csv,45d81a1cbf51d1d6;8c4615f42b8a9502;290318c8cc2d...,R001_rent_collections,NaN,2024
387,2024-11,2024-11-30,ARS,Family Business,Tigre 28,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,370000.0,0.0,370000.0,370000.0,2,classified,high,False,ledger_canonical.csv,aed940a322ac1744;58f8c6565da79175,R001_rent_collections,NaN,2024
388,2024-11,2024-11-30,ARS,Family Business,Tigre 32,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,447950.0,0.0,447950.0,447950.0,3,classified,high,False,ledger_canonical.csv,ed299090ba4e1f2f;349e77ea1491b6a8;a5e86aedadfa...,R001_rent_collections,NaN,2024
410,2024-12,2024-12-31,ARS,Family Business,NaN,Family Business,Gasto,FB,Gasto,Family Business,Transfer:Gasto,family_withdrawal_candidate,personal_expense,0.0,1467524.0,-1467524.0,1467524.0,1,classified,medium,False,ledger_canonical.csv,4b585bd7fbe907a0,R011_personal_expense_text,review family/informal withdrawal candidate,2024
407,2024-12,2024-12-31,ARS,Family Business,Tigre 01,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,649574.0,0.0,649574.0,649574.0,3,classified,high,False,ledger_canonical.csv,2dfe65796ae0e163;6b8a864f823523f7;30e6325b9ddc...,R001_rent_collections,NaN,2024
408,2024-12,2024-12-31,ARS,Family Business,Tigre 28,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,370000.0,0.0,370000.0,370000.0,2,classified,high,False,ledger_canonical.csv,71582816501d347c;55b1bef3f88b64fd,R001_rent_collections,NaN,2024
409,2024-12,2024-12-31,ARS,Family Business,Tigre 32,Family Business,Inq,Inq,FB,Family Business,Cobros:Renta,operating_revenue,rent,447950.0,0.0,447950.0,447950.0,3,classified,high,False,ledger_canonical.csv,b92fc86cecf56a99;610a09c843b75ffd;2be8ac526ba4...,R001_rent_collections,NaN,2024

In [10]:
# group_cols = [
#     c for c in [
#         "semantic_bucket",
#         "semantic_subbucket",
#         "cash_path",
#         "Box",
#         "box",
#         "governance_box",
#         "payer",
#         "receiver",
#         "actor",
#         "counterparty",
#     ]
#     if c in fb2024.columns
# ]

# fb_summary = (
#     fb2024
#     .groupby(group_cols, dropna=False)[value_col]
#     .sum()
#     .reset_index()
#     .sort_values(value_col, ascending=False)
# )

# display(fb_summary.head(100))
# export_table(fb_summary, repo_root, "debug_2024_fb_drain_trace.csv")

In [11]:
draws_by_type = metrics[
    metrics["metric_id"].astype(str).isin([
        "DIST.DRAWS.PERSONAL",
        "DIST.DIVIDENDS",
        "DIST.DRAWS.BY_TYPE",
        "DQ.UNKNOWN.AMOUNT",
    ])
].copy()

display(
    draws_by_type[
        [
            c for c in [
                "metric_id",
                "dashboard_section",
                "Currency",
                "period",
                "dimension_name",
                "dimension_value",
                "value",
                "value_status",
                "source_table",
                "caveat",
            ]
            if c in draws_by_type.columns
        ]
    ].sort_values(["metric_id", "Currency", "period", "dimension_name", "dimension_value"])
)

               metric_id             dashboard_section Currency period      dimension_name   dimension_value       value value_status                     source_table caveat
45        DIST.DIVIDENDS  2. Funding and distributions      ARS   2022                                               0.0    available  monthly_operating_statement.csv
46        DIST.DIVIDENDS  2. Funding and distributions      ARS   2023                                               0.0    available  monthly_operating_statement.csv
48        DIST.DIVIDENDS  2. Funding and distributions      ARS   2024                                               0.0    available  monthly_operating_statement.csv
50        DIST.DIVIDENDS  2. Funding and distributions      ARS   2025                                               0.0    available  monthly_operating_statement.csv
52        DIST.DIVIDENDS  2. Funding and distributions      ARS   2026                                         1367384.0    available  monthly_operating_statement.csv
47        DIST.DIVIDENDS  2. Funding and distributions      USD   2023                                               0.0    available  monthly_operating_statement.csv
49        DIST.DIVIDENDS  2. Funding and distributions      USD   2024                                             100.0    available  monthly_operating_statement.csv
51        DIST.DIVIDENDS  2. Funding and distributions      USD   2025                                               0.0    available  monthly_operating_statement.csv
53        DIST.DIVIDENDS  2. Funding and distributions      USD   2026                                             380.0    available  monthly_operating_statement.csv
183   DIST.DRAWS.BY_TYPE  2. Funding and distributions      ARS   2022  semantic_subbucket  personal_expense   4361538.0    available  monthly_flow_semantic_split.csv
184   DIST.DRAWS.BY_TYPE  2. Funding and distributions      ARS   2023  semantic_subbucket  personal_expense   8588546.0    available  monthly_flow_semantic_split.csv
185   DIST.DRAWS.BY_TYPE  2. Funding and distributions      ARS   2024  semantic_subbucket  personal_expense  13558336.0    available  monthly_flow_semantic_split.csv
187   DIST.DRAWS.BY_TYPE  2. Funding and distributions      ARS   2025  semantic_subbucket  personal_expense  34485689.0    available  monthly_flow_semantic_split.csv
188   DIST.DRAWS.BY_TYPE  2. Funding and distributions      ARS   2026  semantic_subbucket          dividend   1367384.0    available  monthly_flow_semantic_split.csv
189   DIST.DRAWS.BY_TYPE  2. Funding and distributions      ARS   2026  semantic_subbucket  personal_expense  25148626.0    available  monthly_flow_semantic_split.csv
186   DIST.DRAWS.BY_TYPE  2. Funding and distributions      USD   2024  semantic_subbucket          dividend       100.0    available  monthly_flow_semantic_split.csv
190   DIST.DRAWS.BY_TYPE  2. Funding and distributions      USD   2026  semantic_subbucket          dividend       380.0    available  monthly_flow_semantic_split.csv
36   DIST.DRAWS.PERSONAL  2. Funding and distributions      ARS   2022                                         4361538.0    available  monthly_operating_statement.csv
37   DIST.DRAWS.PERSONAL  2. Funding and distributions      ARS   2023                                         8588546.0    available  monthly_operating_statement.csv
39   DIST.DRAWS.PERSONAL  2. Funding and distributions      ARS   2024                                        13558336.0    available  monthly_operating_statement.csv
41   DIST.DRAWS.PERSONAL  2. Funding and distributions      ARS   2025                                        34485689.0    available  monthly_operating_statement.csv
43   DIST.DRAWS.PERSONAL  2. Funding and distributions      ARS   2026                                        26516010.0    available  monthly_operating_statement.csv
38   DIST.DRAWS.PERSONAL  2. Funding and distributions      USD   2023                                               0.0    available  monthly_operating_statement.csv
40   DIST.DRAWS.PERSONAL  2. Funding and distributions      USD   2024                                             100.0    available  monthly_operating_statement.csv
42   DIST.DRAWS.PERSONAL  2. Funding and distributions      USD   2025                                               0.0    available  monthly_operating_statement.csv
44   DIST.DRAWS.PERSONAL  2. Funding and distributions      USD   2026                                             380.0    available  monthly_operating_statement.csv
63     DQ.UNKNOWN.AMOUNT   6. Data quality and caveats      ARS   2022                                               0.0    available  monthly_operating_statement.csv
64     DQ.UNKNOWN.AMOUNT   6. Data quality and caveats      ARS   2023                                               0.0    available  monthly_operating_statement.csv
66     DQ.UNKNOWN.AMOUNT   6. Data quality and caveats      ARS   2024                                               0.0    available  monthly_operating_statement.csv
68     DQ.UNKNOWN.AMOUNT   6. Data quality and caveats      ARS   2025                                               0.0    available  monthly_operating_statement.csv
70     DQ.UNKNOWN.AMOUNT   6. Data quality and caveats      ARS   2026                                               0.0    available  monthly_operating_statement.csv
65     DQ.UNKNOWN.AMOUNT   6. Data quality and caveats      USD   2023                                               0.0    available  monthly_operating_statement.csv
67     DQ.UNKNOWN.AMOUNT   6. Data quality and caveats      USD   2024                                               0.0    available  monthly_operating_statement.csv
69     DQ.UNKNOWN.AMOUNT   6. Data quality and caveats      USD   2025                                               0.0    available  monthly_operating_statement.csv
71     DQ.UNKNOWN.AMOUNT   6. Data quality and caveats      USD   2026                                               0.0    available  monthly_operating_statement.csv

## 3. Comentarios profesionales de overview

Este bloque no busca cerrar diagnóstico legal/contable, sino dejar explícitas las tensiones que deben discutirse con contadores y gente de negocio.

In [12]:
overview_comments = pd.DataFrame([
    {"tema": "Operación", "comentario": "El resultado operativo debe aislar rentas y OPEX reales de propiedad. Funding, deuda, dividendos y gasto personal van fuera."},
    {"tema": "Distribución", "comentario": "Si retiros/dividendos absorben más que el resultado operativo, el problema es de política de distribución y gobernanza, no solo de rentabilidad."},
    {"tema": "Caja", "comentario": "Caja validada debe permanecer s/d si no hay validated_cash_close frontend-safe. No se debe usar daily_cash_position como caja reportable."},
    {"tema": "Deuda", "comentario": "La deuda interna muestra quién financió o adelantó fondos. Debe tratarse como stock/flow separado y reconciliado."},
    {"tema": "Entidad", "comentario": "Hace falta decidir perspectiva: PM, familia consolidada o sistema patrimonial total. Activo/pasivo depende de esa entidad."},
    {"tema": "2026", "comentario": "Si 2026 es año parcial, todos los cuadros deben marcar YTD para evitar comparaciones engañosas."},
])
display(overview_comments)
export_table(overview_comments, repo_root, "overview_professional_comments.csv")

           tema                                         comentario
0     Operación  El resultado operativo debe aislar rentas y OP...
1  Distribución  Si retiros/dividendos absorben más que el resu...
2          Caja  Caja validada debe permanecer s/d si no hay va...
3         Deuda  La deuda interna muestra quién financió o adel...
4       Entidad  Hace falta decidir perspectiva: PM, familia co...
5          2026  Si 2026 es año parcial, todos los cuadros debe...

wrote: /home/matias/repos/accounting-backend/out/professional_pack/latest/tables/overview_professional_comments.csv rows=6 cols=2

PosixPath('/home/matias/repos/accounting-backend/out/professional_pack/latest/tables/overview_professional_comments.csv')

## 4. Export report

Exporta HTML y Markdown simples a `out/professional_pack/latest/`.

In [13]:
md_path = write_markdown_report(
    repo_root,
    "01_balance_dashboard_overview.md",
    "01 — Balance dashboard overview",
    [
        ("Executive summary", "La operación, funding/distribuciones, caja y deuda se presentan como capas separadas. ARS y USD conviven por fila, sin sumarse."),
        ("Overview table", overview_table),
        ("Extended QA", extended_qa),
        ("Professional comments", overview_comments),
    ],
)
html_path = write_html_report(
    repo_root,
    "01_balance_dashboard_overview.html",
    "01 — Balance dashboard overview",
    [
        ("Executive summary", "La operación patrimonial parece positiva, pero la distribución/retiros, caja no auditada y deuda interna requieren tratamiento separado."),
        ("Overview table", overview_table),
        ("Extended QA", extended_qa),
        ("Professional comments", overview_comments),
    ],
)
print("markdown:", md_path.relative_to(repo_root))
print("html:", html_path.relative_to(repo_root))

markdown: out/professional_pack/latest/markdown/01_balance_dashboard_overview.md
html: out/professional_pack/latest/html/01_balance_dashboard_overview.html